# Data Cleaning Using Pandas

### Objective

In this notebook, we will:
- Load the Student Score dataset.
- Identify missing values.
- Handle missing values.
- Detect duplicate records.
- Remove duplicates.
- Generate descriptive statistics.

**Expected Outcome:** A clean dataset is prepared for further analysis.

In [33]:
# Import Pandas
import pandas as pd

## Step 1: Load the Dataset

Load the CSV file into a Pandas DataFrame.

In [34]:
# Load dataset
df = pd.read_csv("/content/student_scores_dirty.csv")

# Display first five rows
df.head()

   Student_ID       Name  Hours_Studied  Attendance  Scores
0           1  Student_1            2.5        85.0    21.0
1           2  Student_2            5.1        92.0    47.0
2           3  Student_3            3.2        78.0    27.0
3           4  Student_4            8.5        98.0    75.0
4           5  Student_5            3.5        81.0    30.0

## Step 2: Check Missing Values

The `isnull().sum()` function counts missing values in each column.

In [35]:
print("Missing Values:")
df.isnull().sum()

Missing Values:

Student_ID       0
Name             0
Hours_Studied    1
Attendance       1
Scores           1
dtype: int64

## Step 3: Handle Missing Values

Fill missing numerical values with the column mean.

> If the dataset contains no missing values, the dataset remains unchanged.

In [36]:
numeric_columns = df.select_dtypes(include=["number"]).columns

df[numeric_columns] = df[numeric_columns].fillna(
    df[numeric_columns].mean()
)

df.head()

   Student_ID       Name  Hours_Studied  Attendance  Scores
0           1  Student_1            2.5        85.0    21.0
1           2  Student_2            5.1        92.0    47.0
2           3  Student_3            3.2        78.0    27.0
3           4  Student_4            8.5        98.0    75.0
4           5  Student_5            3.5        81.0    30.0

## Step 4: Verify Missing Values Again

Confirm that all missing values have been handled.

In [37]:
df.isnull().sum()

Student_ID       0
Name             0
Hours_Studied    0
Attendance       0
Scores           0
dtype: int64

## Step 5: Check for Duplicate Records

The `duplicated()` function identifies duplicate rows.

In [38]:
print("Number of Duplicate Rows:")
print(df.duplicated().sum())

Number of Duplicate Rows:
1

## Step 6: Remove Duplicate Records

Remove duplicate rows using `drop_duplicates()`.

In [39]:
df = df.drop_duplicates()

print("Dataset Shape After Removing Duplicates:")
print(df.shape)

Dataset Shape After Removing Duplicates:
(25, 5)

## Step 7: Display Dataset Statistics

Generate descriptive statistics for numerical columns.

In [40]:
df.describe()

       Student_ID  Hours_Studied  Attendance     Scores
count   25.000000      25.000000   25.000000  25.000000
mean    13.000000       5.087680   86.598400  49.724800
std      7.359801       2.499872    8.077669  23.607344
min      1.000000       1.100000   70.000000  17.000000
25%      7.000000       2.700000   81.000000  30.000000
50%     13.000000       5.100000   86.960000  47.000000
75%     19.000000       7.400000   93.000000  69.000000
max     25.000000       9.200000   99.000000  88.000000

## Step 8: Display Dataset Information

Check the structure and data types after cleaning.

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     25 non-null     int64
 1   Name           25 non-null     object
 2   Hours_Studied  25 non-null     float64
 3   Attendance     25 non-null     float64
 4   Scores         25 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 1.2+ KB

## Step 9: Save the Cleaned Dataset

Store the cleaned dataset as a new CSV file.

In [42]:
df.to_csv("student_scores_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Conclusion

In this notebook, we successfully:

- Loaded the dataset.
- Identified missing values.
- Filled missing numerical values.
- Checked for duplicate records.
- Removed duplicate rows.
- Analyzed dataset statistics.
- Saved the cleaned dataset.

**Expected Outcome Achieved:** A clean dataset is prepared for further analysis.