# Machine Learning Basics using Scikit-learn

## Objective

In this notebook, we will:

- Understand Supervised Learning.
- Split the dataset into Training and Testing sets.
- Train a Linear Regression model.
- Make predictions.
- Evaluate the model.

**Expected Outcome:** Understand the fundamentals of Machine Learning using Linear Regression.

In [49]:
# Import Required Libraries
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Step 1: Load the Dataset

Load the Student Score dataset into a Pandas DataFrame.

In [50]:
df = pd.read_csv("/content/student_scores.csv")

df.head()

   Student_ID       Name  Hours_Studied  Attendance  Scores
0           1  Student_1            2.5          85      21
1           2  Student_2            5.1          92      47
2           3  Student_3            3.2          78      27
3           4  Student_4            8.5          98      75
4           5  Student_5            3.5          81      30

## Step 2: Select Features and Target

- Feature (X): Hours Studied
- Target (y): Scores

The model will learn the relationship between study hours and exam scores.

In [51]:
X = df[["Hours_Studied"]]

y = df["Scores"]

print(X.head())
print(y.head())

   Hours_Studied
0            2.5
1            5.1
2            3.2
3            8.5
4            3.5
0    21
1    47
2    27
3    75
4    30
Name: Scores, dtype: int64

## Step 3: Split the Dataset

Split the dataset into:

- Training Set (80%)
- Testing Set (20%)

The training set is used to train the model, while the testing set evaluates its performance.

In [52]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Samples: 20
Testing Samples: 5

## Step 4: Train the Linear Regression Model

Linear Regression is a supervised learning algorithm that predicts continuous values by fitting a straight line to the data.

In [53]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

## Step 5: Make Predictions

Use the trained model to predict scores for the testing dataset.

In [54]:
y_pred = model.predict(X_test)

print("Predicted Scores:")
print(y_pred)

Predicted Scores:
[83.18814104 27.03208774 27.03208774 69.63323162 59.95115347]

## Step 6: Compare Actual and Predicted Scores

Create a table to compare actual and predicted values.

In [55]:
results = pd.DataFrame({
    "Actual Score": y_test.values,
    "Predicted Score": y_pred.round(2)
})

results

   Actual Score  Predicted Score
0            81            83.19
1            30            27.03
2            21            27.03
3            76            69.63
4            62            59.95

## Step 7: Evaluate the Model

Common evaluation metrics include:

- Mean Absolute Error (MAE)
- Mean Squared Error (MSE)
- R² Score

In [57]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", round(mae,2))
print("Mean Squared Error (MSE):", round(mse,2))
print("R² Score:", round(r2,2))

Mean Absolute Error (MAE): 3.92
Mean Squared Error (MSE): 18.94
R² Score: 0.97

## Step 8: Predict a New Student's Score

Predict the score of a student who studies for **6.5 hours**.

In [59]:
new_prediction = model.predict([[6.5]])

print("Predicted Score for 6.5 Study Hours:", round(new_prediction[0],2))

Predicted Score for 6.5 Study Hours: 65.76

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

# Conclusion

In this notebook, we successfully:

- Loaded the dataset.
- Understood Supervised Learning.
- Split the dataset into training and testing sets.
- Trained a Linear Regression model.
- Made predictions.
- Evaluated model performance.
- Predicted the score of a new student.

**Expected Outcome Achieved:** Machine Learning fundamentals using Linear Regression were successfully demonstrated.